<testsuites id="" name="" tests="18" failures="1" skipped="0" errors="0" time="18.622602999999998">
<testsuite name="tests\catalog.spec.js" timestamp="2025-04-21T11:14:05.755Z" hostname="" tests="2" failures="0" skipped="0" time="6.984" errors="0">
<testcase name="Catalog Feature - Products loaded within catalog are verified against api reponse" classname="tests\catalog.spec.js" time="4.524">
</testcase>
<testcase name="Catalog Feature - Adding or Removing Products to cart will increase or decrease number of items in cart" classname="tests\catalog.spec.js" time="2.46">
</testcase>
</testsuite>
<testsuite name="tests\login.spec.js" timestamp="2025-04-21T11:14:05.755Z" hostname="" tests="8" failures="0" skipped="0" time="16.919" errors="0">
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for standard_user" classname="tests\login.spec.js" time="4.054">
</testcase>
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for locked_out_user" classname="tests\login.spec.js" time="1.306">
</testcase>
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for problem_user" classname="tests\login.spec.js" time="1.012">
</testcase>
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for performance_glitch_user" classname="tests\login.spec.js" time="6.044">
</testcase>
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for error_user" classname="tests\login.spec.js" time="0.865">
</testcase>
<testcase name="Login Feature - Login Tests for Multiple Users Scenario › Login Scenario for visual_user" classname="tests\login.spec.js" time="0.917">
</testcase>
<testcase name="Login Feature - Login and Logout Successfully Scenario" classname="tests\login.spec.js" time="1.852">
</testcase>
<testcase name="Login Feature - Login Negative Path -Incorrect Password Scenario" classname="tests\login.spec.js" time="0.869">
</testcase>
</testsuite>
<testsuite name="tests\order.spec.js" timestamp="2025-04-21T11:14:05.755Z" hostname="" tests="1" failures="0" skipped="0" time="4.749" errors="0">
<testcase name="Order Feature - The user performs an order successfully" classname="tests\order.spec.js" time="4.749">
</testcase>
</testsuite>
<testsuite name="tests\pet.api.spec.js" timestamp="2025-04-21T11:14:05.755Z" hostname="" tests="4" failures="0" skipped="0" time="6.579" errors="0">
<testcase name="Pet Service API Tests › Pet Service - Get pet by id" classname="tests\pet.api.spec.js" time="2.147">
</testcase>
<testcase name="Pet Service API Tests › Pet Service - Update existing pet" classname="tests\pet.api.spec.js" time="2.154">
</testcase>
<testcase name="Pet Service API Tests › Pet Service - Delete pet" classname="tests\pet.api.spec.js" time="2.14">
</testcase>
<testcase name="Pet Service API Tests › Pet Service - Get deleted pet should fail" classname="tests\pet.api.spec.js" time="0.138">
</testcase>
</testsuite>
<testsuite name="tests\store.api.spec.js" timestamp="2025-04-21T11:14:05.755Z" hostname="" tests="3" failures="1" skipped="0" time="4.472" errors="0">
<testcase name="Store Service API Tests › Store Service - Get order by id" classname="tests\store.api.spec.js" time="2.158">
</testcase>
<testcase name="Store Service API Tests › Store Service - Delete order" classname="tests\store.api.spec.js" time="2.179">
</testcase>
<testcase name="Store Service API Tests › Store Service - Get deleted order should fail" classname="tests\store.api.spec.js" time="0.135">
<failure message="store.api.spec.js:31:7 Store Service - Get deleted order should fail" type="FAILURE">
<![CDATA[  tests\store.api.spec.js:31:7 › Store Service API Tests › Store Service - Get deleted order should fail 

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "API Error: 404"
    Received string:    "Expected error but got success"

      34 |       throw new Error('Expected error but got success'); // safety fallback
      35 |     } catch (err) {
    > 36 |       expect(err.message).toContain('API Error: 404');
         |                           ^
      37 |       expect(err.message).toContain('Order not found');
      38 |     }
      39 |   });
        at C:\Repo\bg-js-gaming-automation\tests\store.api.spec.js:36:27

    Error Context: test-results\tests-store.api-Store-Serv-e6cf4-t-deleted-order-should-fail\error-context.md
]]>
</failure>
<system-out>
<![CDATA[
[[ATTACHMENT|test-results\tests-store.api-Store-Serv-e6cf4-t-deleted-order-should-fail\error-context.md]]
]]>
</system-out>
</testcase>
</testsuite>
</testsuites>